# environment must be first imported using:
# $ export $(cat .env)

version: '3.7'

networks:
  traefik-public:
    external: true

services:

  # This image is intentionally public, so the SSL pinning salt for X-Pin-Challenge would be more easily accessible
  # not only from the client app, but also from the wide public (intentional mistake, otherwise this would reside in thinxcloud repo).
  pinserver:
    image: registry.thinx.cloud:5000/pinserver:latest
    environment:
      - 'SALT=${SALT}'
    ports:
      - 8888:8888
    networks:
      - traefik-public
    volumes:
      - '/mnt/gluster/kybersoutez/data:/usr/src/app/data'
      - '/mnt/gluster/kybersoutez/pin.json:/usr/src/app/pin.json'

    deploy:
      resources:
        reservations:
          cpus: '0.1'
          memory: 32M
        limits:
          cpus: '0.1'
          memory: 32M
      labels:
        - "traefik.http.services.ssl-pinning.loadbalancer.server.port=8888"
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"

        - "traefik.http.routers.ssl-pinning-https.rule=Host(`${PINNING_HOSTNAME}`)"
        - "traefik.http.routers.ssl-pinning-https.entrypoints=https"
        - "traefik.http.routers.ssl-pinning-https.tls=true"
        - "traefik.http.routers.ssl-pinning-https.tls.certresolver=le"

        - traefik.http.routers.ssl-pinning-https.middlewares=error-pages-middleware

        - swarmpit.service.deployment.autoredeploy=true
